language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- mysql < ./ci/asset/create_test_schmea.sql;
- npm link .
script:
- npm run test
- npm run cover
- npm run report
